### ISSUE TITLE
错误链接的 url https://www.darmau.com/

### ISSUE THREAD

**Issue by essesoul** [zhaodaoai/Makers-Union#18]
```
请输入该错误链接的 url
https://www.darmau.com/
四号链接无法访问
![image](https://user-images.githubusercontent.com/58624474/118345136-2f034580-b565-11eb-98ad-8c2b2d3ef1a0.png)

```

**Comment by yzqzss** [comment]
https://github.com/saveweb/doing/issues/10#issuecomment-877964773

**Comment by yzqzss** [comment]
darmau.com: 该域名现已过期2个月。

另外，您这个项目看起来好像也停止维护了。。。

**Comment by tvvocold** [comment]
已删除 https://github.com/zhaodaoai/Makers-Union/commit/50fca65cd20845390f61a9bcfb5c7c5d2228787e

**Comment by yzqzss** [comment]
对了，请问您还能联系到这个博主吗？（他的联系方式）
